# Generated by Django 3.2.8 on 2021-11-15 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20211115_2256'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dp',
            new_name='profilePicture',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favAlbums',
            field=models.ManyToManyField(to='music.Album'),
        ),
        migrations.AddField(
            model_name='user',
            name='favSongs',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='shukla', max_length=50),
            preserve_default=False,
        ),
    ]
